# Generated by Django 3.0.5 on 2021-02-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
