# Generated by Django 3.0.5 on 2021-02-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savithripuram', '0002_auto_20210214_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
